name = "esp-activation-worker"
main = "worker.js"
compatibility_date = "2025-01-01"

# =========================
# KV Namespace Binding
# =========================
kv_namespaces = [
  { 
    binding = "ACTIVATION_CODES", 
    id = "96f0fd8999784f2b94b6c6e726f66ca8" 
  }
]

# =========================
# Optional (safe to keep)
# =========================
workers_dev = true
